### ISSUE TITLE
RxJS / Observables

### ISSUE THREAD

**Issue by liamzdenek** [charmCityJs/talks#143]
**Your name:** Liam Zdenek

**Your talk idea, described briefly:** RxJS is a library for performing functional mutations (filter/map/etc) on a time-distributed set (clicks or any other repeatable callback). This is a beginner introduction, but if the audience is familiar, I can go in greater detail.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** RxJS/Observables

**CCJS Slack username:**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 15 mins

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@liamzdenek Are you available next Wednesday, January 3, to give this talk?

**Comment by liamzdenek** [comment]
I can do this on Jan 3. Would you prefer live demo, powerpoint, or spoken only?

**Comment by esauter5** [comment]
Format is up to you. It's good to have something to put on screen to keep the audience engaged whether it be a powerpoint, live demo, or some combination of both.

Also as far as the beginner vs. deeper dive, I think a safe rule is to underestimate what you think the audience knows. That while you'll reach most of the audience and even if people are more senior, theres a chance they haven't done much with observables. I've found that as a speaker it's very easy to assume everyone knows something because you personally are very comfortable with it.

Also, I can't remember any talks on this topic in awhile so it should be a great learning experience for many 😄 . Looking forward to it!

**Comment by esauter5** [comment]
I enjoyed the demo the other night. Thanks @liamzdenek!
