### ISSUE TITLE
Everything is Terrible: the rise and fall of best practices

### ISSUE THREAD

**Issue by naterkane** [charmCityJs/talks#45]
Your name: Nater Kane

Your idea: Over the last couple of years, what had been considered tried and true best practices have fallen by the wayside with the advent of clientside frameworks. I look to explore how this happened, and what we can do to get back on track to create not only humane experiences for users, but also humane experiences for our fellow developers.

Approx length: 15-20

**Comment by rayners** [comment]
I like the sound of this!

**Comment by naterkane** [comment]
yay! [+1]

On Thu, Nov 5, 2015 at 9:40 AM, David Raynes <notifications@github.com>
wrote:

> I like the sound of this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charmCityJs/talks/issues/45#issuecomment-154078916>.
>



-- 
Best,
Nater Kane

**Comment by Oladele** [comment]
I'm also interested in this. I love hearing anything about "what even is software development" humane or not. Why? Because 5 years into it, after first being introduced to sw dev through (nightmarish) mega-enterprise J2EE project and then going on to self-motivated relatively cushy "easy to start and deliver" server-side Rails dev and now, complicated (to me), client-side JS, I'm super keen to hear anything anyone has to say about sw development as a profession or practice (humane or not) in the real world...frameworks, technologies, people, coffee, ops, priorities...and all. Not saying you can or should get into all that. Just a long way of saying...good talk proposal. Let's hear it.
